version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - apt-get update -y
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - apt-get install -y libpq-dev libzip-dev
      - apt-get install -y php-pgsql
      - apt-get install -y sqlite3 libsqlite3-dev
      - curl -sS https://getcomposer.org/installer -o composer-setup.php
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - composer install --no-interaction --no-progress --prefer-dist
      - npm install
  build:
    commands:
      - php artisan key:generate
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%d)
proxy:
  upload-artifacts: true
  logs: yes
